# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Zeabur's official command line tool"
  homepage "https://zeabur.com"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zeabur/cli/releases/download/v0.2.0/zeabur_0.2.0_darwin_arm64"
      sha256 "3e6f1175c0ad66f7975e333c0f15f0f8b3d1dbac0074870612edc03fc8e150e4"

      def install
        bin.install "zeabur_0.2.0_darwin_arm64" => "zeabur"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zeabur/cli/releases/download/v0.2.0/zeabur_0.2.0_darwin_amd64"
      sha256 "0624d38b11fd6d841cea54d8c0849a89d691c2256539dd47cc2bd5278ca3fabb"

      def install
        bin.install "zeabur_0.2.0_darwin_amd64" => "zeabur"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zeabur/cli/releases/download/v0.2.0/zeabur_0.2.0_linux_arm64"
      sha256 "6ca44b1d73a290eef6f57a303f24219c488b1d39909744c2d6f5d76d30cc043d"

      def install
        bin.install "zeabur_0.2.0_linux_arm64" => "zeabur"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zeabur/cli/releases/download/v0.2.0/zeabur_0.2.0_linux_amd64"
      sha256 "d016213eb899f0515b506e336f8d0d1d4aaa2556ff7d8bc370e16d956da9ee1b"

      def install
        bin.install "zeabur_0.2.0_linux_amd64" => "zeabur"
      end
    end
  end
end
