# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Zeabur's official command line tool"
  homepage "https://zeabur.com"
  version "0.2.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zeabur/cli/releases/download/0.2.4/zeabur_0.2.4_darwin_arm64"
      sha256 "50f26990b7cc00eeb2d87104591de407beb2682a3be601a885d7d13b0b7b72c3"

      def install
        bin.install "zeabur_0.2.4_darwin_arm64" => "zeabur"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zeabur/cli/releases/download/0.2.4/zeabur_0.2.4_darwin_amd64"
      sha256 "6f07e3f939a50f151faade6a3c6ef7e94046e5ebb52c1e4db68bfc8cacec0cff"

      def install
        bin.install "zeabur_0.2.4_darwin_amd64" => "zeabur"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zeabur/cli/releases/download/0.2.4/zeabur_0.2.4_linux_arm64"
      sha256 "3985939e48d1211858b86215307b0c95436df14e4543d0da9615cd33f850f612"

      def install
        bin.install "zeabur_0.2.4_linux_arm64" => "zeabur"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zeabur/cli/releases/download/0.2.4/zeabur_0.2.4_linux_amd64"
      sha256 "3234b60d401087da893affdc43f254174500867c0068b4724a39afc21067fbca"

      def install
        bin.install "zeabur_0.2.4_linux_amd64" => "zeabur"
      end
    end
  end
end
